# Generated by Django 3.1.7 on 2021-03-03 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rol', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('apellido', models.CharField(max_length=250)),
                ('documento', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=20)),
                ('ciudad', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=50)),
                ('password', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_user_id', models.CharField(max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_user_id', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('rol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rol.rol')),
            ],
        ),
    ]
