# Generated by Django 3.1.7 on 2021-03-05 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rol', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rol',
            name='permissions',
        ),
        migrations.AddField(
            model_name='rol',
            name='permisoAdmin',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rol',
            name='permisoCalidad',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rol',
            name='permisoContactos',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rol',
            name='permisoEstadisticas',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rol',
            name='permisoGestion',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rol',
            name='permisoMonitoreo',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rol',
            name='permisoProcesos',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rol',
            name='permisoResportes',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
