# Generated by Django 3.1.7 on 2021-03-05 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rol', '0002_auto_20210305_1035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rol',
            old_name='permisoResportes',
            new_name='permisoReportes',
        ),
    ]
