# Generated by Django 3.1.7 on 2021-03-05 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rol', '0003_auto_20210305_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rol',
            name='state',
            field=models.CharField(default=1, max_length=200),
        ),
    ]
