from django.db import models


# Create your models here.
class datos_cliente(models.Model):
    NUMERO_CEDULA = models.CharField(max_length=150)
    NUMERO_CEDULA_NUMERICO = models.CharField(max_length=150)
    NOMBRES_Y_APELLIDOS = models.CharField(max_length=150)
    COD_SEXO = models.CharField(max_length=10)
    DESCRIPCION_SEXO = models.CharField(max_length=10)
    COD_CIUDADANIA = models.CharField(max_length=50)
    DESCRIPCION_CIUDADANIA = models.CharField(max_length=30)
    FECH_NACIMIENTO = models.CharField(max_length=150)
    CODIGO_LUGAR_NACIMIENTO = models.CharField(max_length=150)
    CODIGO_NACIONALIDAD = models.CharField(max_length=3)
    DESCRIPCION_NACIONALIDAD = models.CharField(max_length=20)
    CODIGO_ESTADO_CIVIL = models.CharField(max_length=1)
    DESCRIPCION_ESTADO_CIVIL = models.CharField(max_length=10)
    CODIGO_NIVEL_ESTUDIOS = models.CharField(max_length=2)
    DESCRIPCION_NIVEL_ESTUDIOS = models.CharField(max_length=15)
    CODIGO_PROFESION = models.CharField(max_length=3)
    DESCRIPCION_PROFESION = models.CharField(max_length=30)
    NOMBRE_CONYUGUE = models.CharField(max_length=150)
    CEDULA_CONYUGUE = models.CharField(max_length=150)
    FECHA_MATRIMONIO = models.CharField(max_length=10)
    LUG_MATRIMONIO = models.CharField(max_length=10)
    NOMBRES_DEL_PADRE = models.CharField(max_length=150)
    NAC_PAD = models.CharField(max_length=150)
    NUMERO_CEDULA_PADRE = models.CharField(max_length=150)
    NOMBRES_DE_LA_MADRE = models.CharField(max_length=150)
    NAC_MAD = models.CharField(max_length=150)
    NUMERO_CEDULA_MADRE = models.CharField(max_length=150)
    FECH_DEF = models.CharField(max_length=150)
    LUG_DEF = models.CharField(max_length=350)
    LUG_INSC = models.CharField(max_length=350)
    CODIGO_DOMICILIO = models.CharField(max_length=150)
    CALLE_DOMICILIO = models.CharField(max_length=500)
    NUMERO_CASA = models.CharField(max_length=150)
    FECHA_ACTUALIZACION_DATOS = models.CharField(max_length=10)
    GENERO = models.CharField(max_length=1)
    ESTADO_PERSONA = models.CharField(max_length=10)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    state = models.CharField(max_length=200, default=1)
